services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared_proxy_network
    volumes:
      # - ./config:/etc/nginx/templates
      - ./config/templates:/etc/nginx/templates
      - ./config/snippets:/etc/nginx/snippets
      - ./ssl:/etc/nginx/certs
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - CINEKWOK_HOST=cinekwok.com
      - FARFLUNGINFO_HOST=farflunginfo.cinekwok.com
      - COMMENTVERDICT_TEST_CONTAINER=commentverdict_test_api
      - COMMENTVERDICT_TEST_HOST=test.commentverdict.com
      - COMMENTVERDICT_TEST_PORT=8000
      - COMMENTVERDICT_FLOWER_CONTAINER=focus-guard-flower
      - COMMENTVERDICT_FLOWER_HOST=flower-test.commentverdict.com
      - COMMENTVERDICT_FLOWER_PORT=5555
      - COMMENTVERDICT_WEB_CONTAINER=commentverdict-web-portal
      - COMMENTVERDICT_WEB_HOST_1=commentverdict.com
      - COMMENTVERDICT_WEB_HOST_2=app.commentverdict.com
      - COMMENTVERDICT_WEB_PORT=3000
      - COMMENTVERDICT_PROD_CONTAINER=commentverdict_prod_api
      - COMMENTVERDICT_PROD_HOST=api.commentverdict.com
      - COMMENTVERDICT_PROD_PORT=8000

networks:
  shared_proxy_network:
    external: true
